AltBalance.chapter(1) {

  BossModifier.add(:BOSSGARBODOR)
              .set_name("Garbage Menace")
              .set_pkmn(:GARBODOR, 17, :HOARDING, moves: [:POUND, :ACIDSPRAY, :DOUBLESLAP, :ATTRACT], gender: "M", shiny: true, nature: :NAUGHTY, happiness: 255)
              .set_shields(3)
              .set_entry_text("The Garbodor approached!")
              .set_break_effect(2, delete: true)
              .set_break_effect(3, threshold: 0, message: "Garbodor's typing changed!", animation: :NASTYPLOT, typeChange: [:POISON, :DARK])
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 3")
              .set_sos_continuous(true)
              .set_sos_count(6)
              .set_sos_pkmn(1, :TRUBBISH, 12, :STENCH, moves: [:EXPLOSION], iv: 10)

  BossModifier.add(:RIFTGYARADOS1)
              .set_name("Rift Gyarados")
              .set_pkmn(:GYARADOS, 28, :INTIMIDATE, form: 4, moves: [:SHADOWSNEAK, :BITE, :WATERPULSE, :ICEFANG], gender: "M", nature: :NAUGHTY, happiness: 255)
              .set_shields(2)
              .set_break_effect(2, threshold: 0, message: "Rift Gyarados started acting defensive!", animation: :WITHDRAW, statDropCure: true, bossStatChanges: {2=>1})
              .set_break_effect(1, threshold: 0, message: "Rift Gyarados explodes with dark energy!", bossStatChanges: {2 => -1, 4 => -1, 5 => 1}, statusCure: true, typeChange: [:WATER, :DARK], abilitychange: :STRONGJAW)

}

AltBalance.chapter(2) {

  BossModifier.add(:RIFTGALVANTULA)
              .set_name("Rift Galvantula")
              .set_pkmn(:GALVANTULA, 29, :nil, form: 2, moves: [:ELECTROWEB, :BUGBITE, :CROSSPOISON, :TOXICTHREAD], gender: "F", nature: :HASTY, iv: 20, happiness: 255, ev: [32, 32, 32, 32, 32, 32])
              .set_shields(3)
              .set_entry_text("Joltik gather about the egg...")
              .set_break_effect(3, threshold: 0, formchange: 1, message: "Rift Galvantula hatched out of the egg!", abilitychange: :UNNERVE, movesetUpdate: [:ELECTROWEB, :LUNGE, :CROSSPOISON, :VENOSHOCK], statDropCure: true, playersideChanges: :ToxicSpikes, playersideChangeAnimation: :TOXICSPIKES, playersideChangeMessage: "Broken eggshell was strewn everywhere!")
              .set_break_effect(2, threshold: 0, delete: true, message: "Joltik gather about Galvantula! It's hard to get a clean shot!", bossStatChanges: {2 => 1, 4 => 1})
              .set_break_effect(1, threshold: 0, message: "Rift Galvantula is enraged!", abilitychange: :MERCILESS, movesetUpdate: [:DISCHARGE, :GIGADRAIN, :SLUDGEBOMB, :VENOSHOCK], statusCure: true)
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 2")

  BossModifier.add(:SHADOWMEWTWO)
              .set_name("Shadow Mewtwo")
              .set_pkmn(:MEWTWO, 30, :PRESSURE, moves: [:SHADOWSNEAK, nil, nil, nil], nature: :HARDY, iv: 20, happiness: 0, form: 3, shadow: true, ev: [40, 40, 40, 40, 40, 40])
              .set_shields(2)
              .set_entry_text("Mewtwo's power is building up!")
              .set_entry_effect(message: "KETA: We have to defeat it quickly or else...")
              .set_break_effect(2, threshold: 0, message: "Shadow Mewtwo's power grows!", bossStatChanges: {1=>1, 2=>-1, 3=>1, 4=>-1})
              .set_break_effect(1, threshold: 0, message: "Shadow Mewtwo retreats into its shell...", statDropCure: true, bossStatChanges: {2=>1, 4=>1}, weatherChange: :SHADOWSKY, weatherCount: 5, weatherChangeMessage: "Mewtwo's power darkens the sky!")

  BossModifier.add(:RIFTVOLCANION)
              .set_name("Rift Volcanion")
              .set_pkmn(:VOLCANION, 28, :NEUTRALIZINGGAS)
              .set_shields(4)

}

AltBalance.chapter(3) {

  BossModifier.add(:BOSSDUSKNOIR)
              .set_name("Dusknoir")
              .set_pkmn(:DUSKNOIR, 38, :TECHNICIAN, ev: HPATK)
              .set_shields(2)
              .set_entry_text("The Dusknoir is threatening you.")
              .set_break_effect(2, threshold: 0, message: "Dusknoir is about to throw hands!", movesetUpdate: [:SHADOWPUNCH, :WILLOWISP, :ICEPUNCH, :THUNDERPUNCH], statDropCure: true, bossStatChanges: {1=>1, 2=>1})
              .set_break_effect(1, delete: true, threshold: 0, message: "Dusknoir is out of hands to throw! It's throwing its feet now!", movesetUpdate: [:POLTERGEIST, :SHADOWSNEAK, :ICEPUNCH, :THUNDERPUNCH], statDropCure: true)

}

AltBalance.chapter(4) {

  BossModifier.add(:BOSSCROBAT)
              .set_name("Furious Bat")
              .set_pkmn(:CROBAT, 40, :INFILTRATOR, moves: [:CROSSPOISON, :BITE, :ACROBATICS, :PROTECT], gender: "F", nature: :NAUGHTY, item: :FLYINGGEM, iv: 31, happiness: 255, ev: [40, 40, 40, 40, 40, 40])
              .set_shields(4)
              .set_entry_text("The Crobat attacked with furor!")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 4")
              .set_break_effect(3, threshold: 0, bosssideChanges: :Tailwind, bosssideChangeAnimation: :TAILWIND, bosssideChangeCount: 3, movesetUpdate: [:BRAVEBIRD, :CROSSPOISON, :PROTECT, :LEECHLIFE], statDropCure: true, itemchange: :SITRUSBERRY)
              .set_break_effect(2, delete: true,  threshold: 0, abilitychange: :DELTASTREAM, statusCure: true, message: "BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS BATS")
              .set_sos_continuous(true)
              .set_sos_pkmn(1, :ZUBAT, 34, :INNERFOCUS)
              .set_sos_pkmn(2, :WOOBAT, 34, :UNAWARE)
              .set_sos_pkmn(3, :NOIBAT, 34, :INFILTRATOR)

  BossModifier.add(:RIFTGYARADOS2)
              .set_name("Rift Gyarados")
              .set_pkmn(:GYARADOS, 38, :INTIMIDATE, form: 4, moves: [:PHANTOMFORCE, :WATERFALL, :GRASSYGLIDE, :SCREECH])
              .set_shields(3)
              .set_entry_text("Rift Gyarados is intent on revenge!")
              .set_break_effect(3, threshold: 0, message: "Rift Gyarados's torrential rage engulfs you!", abilitychange: :HYDRATION, typeChange: [:WATER, :DRAGON], movesetUpdate: [:DRAGONRUSH, :LIQUIDATION, :THUNDERFANG, :SCREECH], fieldChange: :WATERSURFACE, fieldChangeMessage: "Rift Gyarados dragged the battle to the lake!")
              .set_break_effect(2, delete: true, threshold: 0, message: "Rift Gyarados burns with fury!", abilitychange: :COMPOUNDEYES, typeChange: [:FIRE, :DRAGON], movesetUpdate: [:DRAGONRUSH, :FIREBLAST, :CRUNCH, :SCREECH], statDropCure: true, fieldChange: :INFERNAL, fieldChangeMessage: "Rift Gyarados conflagarated the arena!")
              .set_break_effect(1, delete: true, threshold: 0, message: "Rift Gyarados's dark aura explodes outward!", abilitychange: :STRONGJAW, typeChange: [:DARK, :DRAGON], movesetUpdate: [:CRUNCH, :THUNDERFANG, :ICEFANG, :FIREFANG], statusCure: true, fieldChange: :DIMENSIONAL, fieldChangeMessage: "Darkness emanates...")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 2")
              .set_sos_continuous(true)
              .set_sos_count(6)
              .set_sos_pkmn(1, :MAGIKARP, 34, :RATTLED, moves: [:WATERFALL])

  BossModifier.add(:WISPYGIRATINA)
              .set_name("Renegade Giratina")
              .set_pkmn(:GIRATINA, 38, :LEVITATE, item: :GRISEOUSORB,moves: [:SHADOWCLAW, :DRAGONCLAW, :DARKPULSE, :ICYWIND],  form: 1, ev: [0, 192, 0, 192, 0, 128])
              .set_shields(3)
              .set_entry_text("GEARA: Destroy them, Giratina! Show them the might of a Legendary Pokémon!")
              .set_break_effect(3, threshold: 0, message: "Giratina's ghastly aura lowered offenses!", statDropCure: true, playerSideStatChanges: {1=>-1, 3=>-1})
              .set_break_effect(2, delete: true, threshold: 0, message: "Giratina reconfigures its strength!", statusCure: true, bossStatChanges: {3=>1}, movesetUpdate: [:SHADOWBALL, :DRAGONPULSE, :BULLDOZE, :ICYWIND])
              .set_break_effect(1, threshold: 0, message: "Giratina's aura enveloped the battlefield!", bossStatChanges: {2=>-1, 4=>-1}, playerSideStatChanges: {2=>-1, 4=>-1})

}

AltBalance.chapter(5) {

  BossModifier.add(:BOSSCONKELDURR)
              .set_name("HARDHAT DAVE")
              .set_pkmn(:CONKELDURR, 45, :IRONFIST, moves: [:DRAINPUNCH, :IRONHEAD, :ICEPUNCH, :THUNDERPUNCH], ev: HPATK)
              .set_shields(3)
              .set_entry_text("Conkeldurr flexes its muscles at you.")
              .set_break_effect(3, threshold: 0, message: "Conkeldurr's muscles are as hard as steel!", itemchange: :ASSAULTVEST, abilitychange: [:IRONFIST, :SOLIDROCK], movesetUpdate: [:DRAINPUNCH, :ICEPUNCH, :THUNDERPUNCH, :BULLETPUNCH], statusCure: true, bossStatChanges: {2=>1})
              .set_break_effect(2, delete: true, threshold: 0, message: "Conkeldurr released its pent-up energy!", abilitychange: [:IRONFIST, :SOLIDROCK, :GUTS], fieldChange: :CITY, :bossSideStatusChanges => [:BURN,"Burn"], bossStatChanges: {1=>1})
              .set_break_effect(1, delete: true, threshold: 0, message: "The miniature city was destroyed!", abilitychange: [:IRONFIST, :SOLIDROCK, :GUTS], statDropCure: true, statusCure: true, fieldChange: :FOREST)
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 2")
              .set_sos_continuous(true)
              .set_sos_pkmn(1, :TIMBURR, 40, :IRONFIST, item: :EVIOLITE, moves: [:COACHING, :HELPINGHAND, :ROCKSLIDE, :HAMMERARM], nature: :ADAMANT)
              .set_sos_pkmn(2, :GURDURR, 40, :IRONFIST, item: :EVIOLITE, moves: [:COACHING, :HELPINGHAND, :ROCKSLIDE, :HAMMERARM], nature: :ADAMANT)

  BossModifier.add(:RIFTCARNIVINE)
              .set_name("Corrupted Carnivine")
              .set_pkmn(:CARNIVINE, 45, :DANCER, form: 1, moves: [:DRAGONDANCE, :POWERWHIP, :DRAGONPULSE, :FLAMETHROWER], ev: ATKSPE)
              .set_shields(2)
              .set_entry_text("Carnivine is dancing the samba!")
              .set_break_effect(2, movesetUpdate: [:SHIFTGEAR, :POWERWHIP, :IRONHEAD, :THOUSANDARROWS], ev: ATKSPE)
              .set_break_effect(1, movesetUpdate: [:QUIVERDANCE, :REVELATIONDANCE, :POLLENPUFF, :FIERYDANCE], ev: HPSPA)
              .set_sos_count(40)
              .set_sos_pkmn(1, :TANGELA, 43, :DANCER, moves: [:FOLLOWME, :REVELATIONDANCE, :POLLENPUFF, :PETALDANCE])
              .set_sos_pkmn(2, :TANGROWTH, 43, :DANCER, moves: [:FOLLOWME, :REVELATIONDANCE, :POLLENPUFF, :ROCKTOMB])

}
AltBalance.chapter(6) {

  BossModifier.add(:TAPUKOKOJUNGLE)
              .set_name("Thunder Warrior")
              .set_pkmn(:TAPUKOKO, 52, :ELECTRICSURGE, shiny: true, moves: [:STEELWING, :NATURESMADNESS, :ELECTRICTERRAIN, :DISCHARGE], nature: :TIMID, ev: SPASPE)
              .set_shields(2)
              .set_break_effect(2, threshold: 0, message: "Tapu Koko is putting in its all!!", movesetUpdate: [:ELECTROBALL, :TAUNT, :ROOST, :DAZZLINGGLEAM], statDropCure: true)

  BossModifier.add(:CRESCGOTHITELLE)
              .set_name("Gothitelle")
              .set_pkmn(:GOTHITELLE, 50, [:COMPETITIVE, :SHADOWTAG])

}

AltBalance.chapter(7) {

  BossModifier.add(:AMETHYSTREGISTEEL)
              .set_name("Iron Guardian")
              .set_pkmn(:REGISTEEL, 55, :FILTER, item: :LEFTOVERS, moves: [:CURSE, :BODYPRESS, :IRONHEAD, :SHOREUP], nature: :CAREFUL, ev: HPSPD)
              .set_shields(3)
              .set_entry_text("The Guardian is watching your every move.")
              .set_break_effect(2, threshold: 0, message: "Registeel prepares to defend!", abilitychange: [:FILTER, :UNAWARE], playersideChanges: :Spikes, playersideChangeAnimation: :SPIKES, playersideChangeCount: 1, playersideChangeMessage: "Spikes were deployed!", statDropCure: true, bossStatChanges: {2=>3, 4=>2})
              .set_break_effect(1, delete: true, threshold: 0, message: "The Guardian summons an assistant!", abilitychange: [:FILTER, :MAGICGUARD], statDropCure: true, effectClear: true, statusCure: true, weatherChange: :HAIL, weatherChangeAnimation: "Hail")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 1")
              .set_sos_count(1)
              .set_sos_pkmn(1, :REGICE, 50, :TURBOJET, item: :LIFEORB, moves: [:ICEBEAM, :THUNDERBOLT, :FOCUSBLAST, :EXPLOSION], nature: :MODEST, ev: SPASPE)

  BossModifier.add(:AMETHYSTREGIROCK)
              .set_name("Stone Guardian")
              .set_pkmn(:REGIROCK, 55, :SHEERFORCE, item: :POWERHERB, moves: [:METEORBEAM, :ROCKSLIDE, :EARTHPOWER, :FIREPUNCH], nature: :NAIVE, ev: [0, 128, 0, 128, 0, 252])
              .set_shields(3)
              .set_entry_text("The Guardian is watching your every move.")
              .set_break_effect(2, threshold: 0, message: "Regirock takes aim at the intruder!", playersideChanges: :StealthRock, playersideChangeCount: true, playersideChangeAnimation: :STEALTHROCK, playersideChangeMessage: "Floating rocks were deployed!", itemchange: :LIFEORB, statDropCure: true, bossStatChanges: {1=>1, 2=>1, 3=>1, 4=>1})
              .set_break_effect(1, delete: true, threshold: 0, message: "The Guardian summons an assistant!", abilitychange: [:FILTER, :MAGICGUARD], statDropCure: true, effectClear: true, statusCure: true, weatherChange: :HAIL, weatherChangeAnimation: "Hail")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 1")
              .set_sos_count(1)
              .set_sos_pkmn(1, :REGICE, 50, :TURBOJET, item: :LIFEORB, moves: [:ICEBEAM, :THUNDERBOLT, :FOCUSBLAST, :EXPLOSION], nature: :MODEST, ev: SPASPE)

  BossModifier.add(:RIFTCHANDELURE)
              .set_name("Rift Chandelure")
              .set_pkmn(:CHANDELURE, 60, :TRACE, item: :FIREGEM, form: 2, moves: [:SHADOWBALL, :AIRSLASH, :FIREBLAST, :WILLOWISP], gender: "M", nature: :TIMID, iv: 31, happiness: 255, ev: [0, 0, 0, 252, 4, 252])
              .set_shields(3)
              .set_entry_text("Otherworldly wind chimes echo through the air...")
              .set_entry_effect(messagemessage: "A feeling of warmth emanates from Rift Chandelure...")
              .set_break_effect(3, threshold: 0, animation: :OMINOUSWIND, message: "The air feels cold and moist...", statDropRefresh: true, bossStatChanges: {3=>1}, itemchange: :WATERGEM, typeChange: [:GHOST, :WATER], movesetUpdate: [:SHADOWBALL, :AIRSLASH, :SURF, :WHIRLPOOL], abilitychange: :PRIMORDIALSEA)
              .set_break_effect(2, threshold: 0, animation: :OMINOUSWIND, message: "A sickly sweet scent attacks your nose...", statDropRefresh: true, bossStatChanges: {2=>1, 4=>1}, itemchange: :GRASSGEM, typeChange: [:GHOST, :GRASS], movesetUpdate: [:SHADOWBALL, :AIRSLASH, :ENERGYBALL, :LEECHSEED], abilitychange: :DAZZLING)
              .set_break_effect(1, threshold: 0, animation: :OMINOUSWIND, message: "The feeling of static is all around...", statDropRefresh: true, bossStatChanges: {5=>1}, itemchange: :ELECTRICGEM, typeChange: [:GHOST, :ELECTRIC], movesetUpdate: [:SHADOWBALL, :AIRSLASH, :THUNDERBOLT, :THUNDERWAVE], abilitychange: :TERAVOLT)

  BossModifier.add(:BOSS_CHAOTICFUSION)
              .set_name("Chaotic Fusion")
              .set_pkmn(:SOLROCK, 55, [:SOLARIDOL, :FILTER], moves: [:EARTHQUAKE, :IRONHEAD, :SOLARFLARE, :TRICKROOM], nature: :ADAMANT, iv: 32, form: 1, item: :FOCUSSASH, ev: HPATK)
              .set_shields(3)
              .set_entry_text("The fused Pokémon suddenly attacked!")
              .set_entry_effect(weatherChange: :SUNNYDAY, weatherChangeAnimation: "Sunny", weatherCount: 5)
              .set_break_effect(3, animation: :FLASH, stateChanges: :TrickRoom, stateChangeCount: 0, stateChangeAnimation: :GRAVITY, weatherChange: :HAIL, weatherChangeAnimation: "Hail", weatherCount: 5, threshold: 0, message: "Lunatone is cloaked in shadow!", itemchange: :SITRUSBERRY, typeChange: [:GHOST, :PSYCHIC], speciesUpdate: :LUNATONE, abilitychange: [:LUNARIDOL, :SHADOWSHIELD, :MAGICGUARD], form: 1, movesetUpdate: [:HOARFROSTMOON, :MOONGEISTBEAM, :PSYCHIC, :EARTHPOWER], CustomMethod: "UniLib.update_base(battler, ev: SPASPE, nature: :MODEST, iv: [31, 31, 31, 31, 31, 31])")
              .set_break_effect(2, animation: :FLASH, weatherChange: :SUNNYDAY, weatherChangeAnimation: "Sunny", weatherCount: 5, threshold: 0, message: "Solrock is embalmed in flame!", itemchange: :FLAMEPLATE, typeChange: [:STEEL, :FIRE], speciesUpdate: :SOLROCK, abilitychange: [:SOLARIDOL, :FLASHFIRE], form: 1, movesetUpdate: [:PHOTONGEYSER, :SUNSTEELSTRIKE, :SOLARFLARE, :TRICKROOM], statDropCure: true, statusCure: true, bossStatChanges: {2=>1, 4=>1}, CustomMethod: "UniLib.update_base(battler, ev: HPATK, nature: :BRAVE, iv: [31, 31, 31, 31, 31, 0])")
              .set_break_effect(1, animation: :FLASH, stateChanges: :TrickRoom, stateChangeCount: 0, stateChangeAnimation: :GRAVITY, weatherChange: :HAIL, weatherChangeAnimation: "Hail", weatherCount: 5, threshold: 0, message: "Lunatone is desperate!", itemchange: :ICIUMZ, typeChange: [:GHOST, :ICE], effectClear: true, speciesUpdate: :LUNATONE, abilitychange: [:LUNARIDOL, :SHADOWSHIELD, :MAGICGUARD], form: 1, movesetUpdate: [:PSYCHIC, :MOONBLAST, :HOARFROSTMOON, :MOONLIGHT], bossStatChanges: {2=>-1, 3=>1, 4=>-1, 5=>1}, CustomMethod: "UniLib.update_base(battler, ev: HPSPA, nature: :MODEST, iv: [31, 31, 31, 31, 31, 31])")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 1")
              .set_sos_count(1)
              .set_sos_pkmn(1, :SOLROCK, 50, :LEVITATE, item: :FLAMEPLATE, moves: [:FLAREBLITZ, :STONEEDGE, :EARTHQUAKE, :EXPLOSION], nature: :BRAVE, ev: HPATK, iv: 32)

  BossModifier.add(:TAPUKOKOMAGRODAR)
              .set_name("Thunder Warrior")
              .set_pkmn(:TAPUKOKO, 55, :ELECTRICSURGE, shiny: true, item: :SITRUSBERRY, moves: [:LIGHTSCREEN, :NATURESMADNESS, :WILDCHARGE, :REFLECT], nature: :JOLLY, ev: ATKSPE)
              .set_shields(2)
              .set_entry_text("The Thunder Warrior is ready to rumble!")
              .set_break_effect(2, threshold: 0, ability: :TELEPATHY, itemchange: :FLYINGGEM, message: "Tapu Koko charges right at you!", statusCure: true, movesetUpdate: [:WILDCHARGE, :ACROBATICS, :ROOST, :FLAREBLITZ], CustomMethod: "UniLib.update_base(battler, ev: PULSE2)")
              .set_break_effect(1, threshold: 0, effectClear: true, statDropCure: true, CustomMethod: "UniLib.update_base(battler, nature: :TIMID, iv: [31, 31, 31, 31, 31, 31])")
              .set_sos_condition("@battle.battlers[battlerIndex].shieldCount < 2")
              .set_sos_count(2)
              .set_sos_pkmn(1, :CHARIZARD, 50, :BLAZE, item: :CHARTIBERRY, ev: SPASPE)
              .set_sos_pkmn(2, :CHARIZARD, 50, :BLAZE, item: :CHARIZARDITEX, moves: [:EARTHQUAKE, :DRAGONCLAW, :FLAREBLITZ, :THUNDERPUNCH], nature: :ADAMANT, ev: ATKSPE)

  BossModifier.add(:BELIAL)
              .set_name("Belial")
              .set_pkmn(:VOLCARONA, 55, :FLAMEBODY, item: :LEFTOVERS, moves: [:FIERYDANCE, :BUGBUZZ, :GIGADRAIN, :ROOST], nature: :TIMID, ev: SPASPE)
              .set_shields(4)
              .set_immunity(:moves)
              .set_immunity(:fieldEffectDamage)
              .set_entry_text("A feisty Volcarona appeared!")
              .set_break_effect(3, threshold: 0, weatherChange: :SUNNYDAY, weatherCount: 5, weatherChangeMessage: "The Sun is bright!", weatherChangeAnimation: "Sunny", itemchange: :LEFTOVERS, bossStatChanges: {2=>1, 4=>1})
              .set_break_effect(2, threshold: 0, bosssideChanges: :Safeguard, bosssideChangeCount: 5, bosssideChangeMessage: "Belial shrouded itself with a Safeguard!", statusCure: true, statDropCure: true, bossStatChanges: {2=>1}, itemchange: :LEFTOVERS)
              .set_break_effect(1, threshold: 0, abilitychange: :SWARM, fieldChange: :FLOWERGARDEN3, fieldChangeMessage: "The field is covered in flowers!", itemchange: :SYNTHETICSEED)
              .set_sos_condition("battler.shieldCount <= sosData[:totalMonCount] - battler.currentSOS")
              .set_sos_continuous(true)
              .set_sos_count(3)
              .set_sos_pkmn(1, :VIVILLON, 50, :COMPOUNDEYES, item: :MENTALHERB, moves: [:SLEEPPOWDER, :HURRICANE, :TAILWIND, :BUGBUZZ], nature: :TIMID, ev: SPASPE)
              .set_sos_pkmn(2, :SHUCKLE, 50, :STURDY, item: :MENTALHERB, moves: [:STEALTHROCK, :INFESTATION, :STICKYWEB, :HELPINGHAND], nature: :BOLD, ev: HPDEF)
              .set_sos_pkmn(3, :VIKAVOLT, 50, :OVERCHARGED, item: :ELECTRICGEM, moves: [:THUNDERBOLT, :BUGBUZZ, :HIDDENPOWERICE, :STICKYWEB], nature: :TIMID, ev: SPASPE)
              .set_sos_pkmn(4, :HERACROSS, 50, :GUTS, item: :FLAMEORB, moves: [:CLOSECOMBAT, :FACADE, :MEGAHORN, :KNOCKOFF], nature: :JOLLY, ev: ATKSPE)

  BossModifier.add(:BOSSGROUDON)
              .set_name("Behemoth Groudon")
              .set_pkmn(:GROUDON, 60, :DROUGHT, moves: [:EARTHQUAKE, :ROCKSLIDE, :TOXIC, :HEATCRASH], nature: :ADAMANT, iv: 31, item: :SITRUSBERRY, ev: [100, 252, 52, 0, 0, 100])
              .set_shields(2)
              .set_immunity(:fieldEffectDamage)
              .set_entry_text("Groudon attacked under command!")
              .set_break_effect(2, threshold: 0, message: "Groudon summoned fierce eruptions!", weatherChange: :SUNNYDAY, weatherChangeAnimation: "Sunny", fieldChange: :VOLCANIC, movesetUpdate: [:EARTHQUAKE, :STONEEDGE, :SWORDSDANCE, :HEATWAVE], statDropCure: true)
              .set_break_effect(1, delete: true, threshold: 0, message: "Magma is churning beneath the surface!", statusCure: true, statDropCure: true, itemchange: :REDORB, bossStatChanges: {2=>1, 4=>1})
              .set_sos_condition("battler.shieldCount <= sosData[:totalMonCount] - battler.currentSOS")
              .set_sos_count(2)
              .set_sos_pkmn(2, :MAGCARGO, 55, :MAGMAARMOR, item: :WHITEHERB, moves: [:SHELLSMASH, :FLAMETHROWER, :EARTHPOWER, :MEMENTO], nature: :TIMID, ev: SPASPE)

  BossModifier.add(:BOSSKYOGRE)
              .set_name("Leviathan Kyogre")
              .set_pkmn(:KYOGRE, 60, :DRIZZLE, moves: [:SURF, :ICEBEAM, :ANCIENTPOWER, :CALMMIND], item: :LEFTOVERS, nature: :MODEST, iv: 31, ev: [252, 0, 128, 128, 0, 0])
              .set_shields(3)
              .set_entry_text("Kyogre's power is overwhelming!")
              .set_break_effect(3, delete: true, threshold: 0, message: "A winter storm is brewing...", animation: :MIST, typeChange: [:WATER, :ICE], weatherChange: :HAIL, weatherChangeAnimation: "Hail", fieldChange: :WATERSURFACE, movesetUpdate: [:WHIRLPOOL, :THUNDERBOLT, :ANCIENTPOWER, :BLIZZARD])
              .set_break_effect(2, threshold: 0, message: "Kyogre dragged the battle underwater!", typeChange: [:WATER, :WATER], fieldChange: :UNDERWATER, animation: :DIVE, movesetUpdate: [:DIVE, :THUNDERBOLT, :ICEBEAM, :SOAK], bossStatChanges: {1=>1, 2=>1, 4=>1}, bossEffect: :AquaRing, bossEffectduration: true, bossEffectanimation: :AQUARING, CustomMethod: "UniLib.update_base(battler, nature: :ADAMANT, ev: ATKSPE)")
              .set_break_effect(1, delete: true, threshold: 0, message: "Kyogre surges with the force of the sea!", fieldChange: :WATERSURFACE, animation: :DIVE, statusCure: true, effectClear: true, statDropCure: true, itemchange: :BLUEORB, movesetUpdate: [:ORIGINPULSE, :THUNDER, :ICEBEAM, :CALMMIND], CustomMethod: "UniLib.update_base(battler, nature: :MODEST, ev: PULSE2)")
              .set_sos_condition("battler.shieldCount < sosData[:totalMonCount] - battler.currentSOS")
              .set_sos_count(3)
              .set_sos_pkmn(1, :WAILORD, 55, :PRESSURE, item: :CHOICESPECS, moves: [:WATERSPOUT, :DARKPULSE, :BLIZZARD, :SCALD], nature: :TIMID, ev: SPASPE)
              .set_sos_pkmn(2, :MILOTIC, 55, :COMPETITIVE, item: :LEFTOVERS, moves: [:SCALD, :DRAGONPULSE, :RECOVER, :MIRRORCOAT], nature: :MODEST, ev: HPSPA)
              .set_sos_pkmn(3, :GYARADOS, 55, :INTIMIDATE, item: :WACANBERRY, moves: [:WATERFALL, :CRUNCH, :ICEFANG, :DRAGONDANCE], nature: :ADAMANT, ev: ATKSPE)

  BossModifier.add(:VALORGIRATINA)
              .set_name("Renegade Giratina")
              .set_pkmn(:GIRATINA, 55, :LEVITATE, item: :GRISEOUSORB, moves: [:SHADOWFORCE, :AURASPHERE, :EARTHPOWER, :DRAGONCLAW], nature: :ADAMANT, form: 1, ev: ATKSPE)
              .set_shields(3)
              .set_entry_text("Giratina is blocking the way forward!")
              .set_break_effect(4, threshold: 0, message: "Giratina's dimensional power simmers...", statDropCure: true, bossStatChanges: {5=>1}, movesetUpdate: [:SHADOWCLAW, :AURASPHERE, :EARTHPOWER, :DRAGONCLAW], playerSideStatChanges: {1=>-2, 3=>-2})
              .set_break_effect(3, threshold: 0, message: "Giratina drew power from the Distortion World!", statDropCure: true, bossStatChanges: {1=>1, 2=>1, 3=>1, 4=>1, 5=>1},
                                :delayedaction => { :delay => 1, :message => "Distorted aura clouds your judgment...", :playerSideStatChanges => { 2=>-1, 4=>-1 },
                                                    :delayedaction => { :delay => 1, :message => "Giratina lays a curse upon you!", :playerEffects => :Curse, :playerEffectsAnimation => :CURSE, :playerEffectsduration => 8, }})
              .set_break_effect(2, delete: true, threshold: 0, message: "Giratina searches for a weakness!", statDropCure: true, statusCure: true, bossStatChanges: {2=>1}, movesetUpdate: [:SHADOWBALL, :EARTHPOWER, :FIREBLAST, :CALMMIND], CustomMethod: "UniLib.update_base(battler, nature: :MODEST, ev: HPSPA)")
              .set_break_effect(1, threshold: 0, message: "The Distortion World seeps out!", bossStatChanges: {2=>1, 4=>1}, playerSideStatChanges: {2=>-1, 4=>-1}, movesetUpdate: [:HEX, :WILLOWISP, :AURASPHERE, :CALMMIND], fieldChange: :HAUNTED, animation: :GRUDGE, statusCure: true, effectClear: true, statDropCure: true)

}