require_relative "UniLib/StandardAPI"
UniLib.set_aggressive_caching

UniLib.include "PokemonOM"
UniLib.include "ExtraMoveFlags"
UniLib.include "Crest"
UniLib.include "BattleEffects"
UniLib.include "Battle"
UniLib.include "Fixes"
UniLib.include "Asset"

UniLib.file_load "Abilities/Atebilities"
UniLib.file_load "Abilities/Custom"
UniLib.file_load "Abilities/Existing"
UniLib.file_load "Abilities/Gen9"

UniLib.file_load "Pokemon/PokeModsGen1"
UniLib.file_load "Pokemon/PokeModsGen2"
UniLib.file_load "Pokemon/PokeModsGen3"
UniLib.file_load "Pokemon/PokeModsGen4"
UniLib.file_load "Pokemon/PokeModsGen5"
UniLib.file_load "Pokemon/PokeModsGen6"
UniLib.file_load "Pokemon/PokeModsGen7"
UniLib.file_load "Pokemon/PokeModsGen8"

UniLib.file_load "Items/Custom"
UniLib.file_load "Items/Gen1Crests"
UniLib.file_load "Items/Gen2Crests"
UniLib.file_load "Items/Gen3Crests"
UniLib.file_load "Items/Gen4Crests"
UniLib.file_load "Items/Gen5Crests"
UniLib.file_load "Items/Gen6Crests"
UniLib.file_load "Items/Gen7Crests"
UniLib.file_load "Items/Gen8Crests"

UniLib.file_load "Maps/Battles"
UniLib.file_load "Maps/Items"
UniLib.file_load "Maps/Misc"

UniLib.file_load "Battles/_Mechanics"
UniLib.file_load "Battles/_EVSpreads"
TrainerModifier.with_defaults(boss: {iv: 31, ev: EVEN60}, sos: {iv: 31, ev: EVEN60}) {
  UniLib.file_load "Battles/_Bosses"
  UniLib.file_load "Battles/_BossesCustom"
  UniLib.file_load "Battles/_Recurring"
  UniLib.file_load "Battles/Virtual"
  UniLib.file_load "Battles/EastGearen"
  UniLib.file_load "Battles/Goldenwood"
  UniLib.file_load "Battles/Route2"
  UniLib.file_load "Battles/Amethyst"
  UniLib.file_load "Battles/Sheridan"
  UniLib.file_load "Battles/Route3"
  UniLib.file_load "Battles/Goldenleaf"
  UniLib.file_load "Battles/WispyTower"
  UniLib.file_load "Battles/WispyRuins"
  UniLib.file_load "Battles/Route4"
  UniLib.file_load "Battles/Blacksteeple"
  UniLib.file_load "Battles/TerajumaBeach"
  UniLib.file_load "Battles/TerajumaJungle"
  UniLib.file_load "Battles/MynoriSea"
  UniLib.file_load "Battles/Route11"
  UniLib.file_load "Battles/Evergreen"
  UniLib.file_load "Battles/Route5"
  UniLib.file_load "Battles/MountTerajuma"
  UniLib.file_load "Battles/Helojak"
  UniLib.file_load "Battles/Kakori"
  UniLib.file_load "Battles/Aquamarine"
  UniLib.file_load "Battles/Teila"
  UniLib.file_load "Battles/Kristilline"
  UniLib.file_load "Battles/GarufanSanctuary"
  UniLib.file_load "Battles/Route6"
  UniLib.file_load "Battles/ValorMountain"
}