RemiX.gym(18) {

  TrainerModifier.add(:SPIRITF, "Diana", 0)
                 .set_pkmn(0, :ROTOM, 100, [:LEVITATE, :DAZZLING], ev: HPSPA)
                 .set_pkmn(1, :ALAKAZAM, 100, [:MAGICGUARD, :DAZZLING], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(2, :SERPERIOR, 100, [:CONTRARY, :DAZZLING], ev: SPASPE)
                 .set_pkmn(3, :WEAVILE, 100, [:PRESSURE, :DAZZLING], moves: [:ICESHARD, :ICEPUNCH, :KNOCKOFF, :LOWKICK], ev: ATKSPE)
                 .set_pkmn(4, :DRAGONITE, 100, [:MULTISCALE, :DAZZLING], ev: ATKSPE)
                 .set_pkmn(5, :SCIZOR, 100, [:TECHNICIAN, :DAZZLING], ev: ATKSPE)
                 .tclass_name_override("Blinding Spirit")

  TrainerModifier.add(:SPIRITM, "Jonathan", 0)
                 .set_pkmn(0, :TOGEKISS, 100, [:SUPERLUCK, :SHEERFORCE], item: :SYNTHETICSEED, moves: [:AIRSLASH, :MOONBLAST, :HEATWAVE, :DEFOG], nature: :QUIET, iv: 32, ev: HPSPA)
                 .set_pkmn(1, :CHANDELURE, 100, [:FLASHFIRE, :SHEERFORCE], item: :CATALYZER, moves: [:SHADOWBALL, :FLASHCANNON, :TRICKROOM, :FIREBLAST], iv: 32, ev: HPSPA)
                 .set_pkmn(2, :TALONFLAME, 100, [:GALEWINGS, :SHEERFORCE], item: :LIFEORB, moves: [:AIRSLASH, :ROOST, :FLAMETHROWER, :QUICKGUARD], nature: :MODEST, ev: SPASPE)
                 .set_pkmn(3, :CONKELDURR, 100, [:GUTS, :SHEERFORCE], moves: [:MACHPUNCH, :DRAINPUNCH, :KNOCKOFF, :METEORMASH], iv: 32)
                 .set_pkmn(4, :ROTOM, 100, [:LEVITATE, :SHEERFORCE], nature: :QUIET, iv: 32, ev: HPSPA)
                 .set_pkmn(5, :PORYGON2, 100, [:TRACE, :SHEERFORCE], nature: :QUIET, iv: 32, ev: HPSPA)
                 .tclass_name_override("Overbearing Spirit")

  TrainerModifier.add(:SPIRITF, "Lexi", 0)
                 .set_pkmn(0, :CRAWDAUNT, 100, [:ADAPTABILITY, :PRIMORDIALSEA], item: :LIFEORB, moves: [:WATERFALL, :KNOCKOFF, :AQUAJET, :CLOSECOMBAT], nature: :ADAMANT, ev: ATKSPE)
                 .set_pkmn(1, :LAPRAS, 100, [:HYDRATION, :PRIMORDIALSEA],moves: [:WATERFALL, :CURSE, :ICESHARD, :REST], ev: HPSPD)
                 .set_pkmn(2, :SCIZOR, 100, [:TECHNICIAN, :PRIMORDIALSEA], item: :FOCUSSASH, ev: [252, 100, 0, 0, 156, 0])
                 .set_pkmn(3, :DRAGONITE, 100, [:MULTISCALE, :PRIMORDIALSEA], moves: [:HURRICANE, :HYDROPUMP, :THUNDER, :ROOST], ev: HPSPA)
                 .set_pkmn(4, :JOLTEON, 100, [:VOLTABSORB, :PRIMORDIALSEA], moves: [:THUNDER, :VOLTSWITCH, :HURRICANE, :HIDDENPOWER], ev: SPASPE)
                 .set_pkmn(5, :AMOONGUSS, 100, [:REGENERATOR, :PRIMORDIALSEA], item: :ROCKYHELMET, ev: [252, 0, 176, 0, 80, 0])
                 .tclass_name_override("Stormy Spirit")

  TrainerModifier.add(:SPIRITM, "Fezz", 0)
                 .set_pkmn(0, :POLITOED, 100, [:DRIZZLE, :LEVITATE], ev: HPDEF)
                 .set_pkmn(1, :SWAMPERT, 100, [:TORRENT, :LEVITATE], moves: [:ICEPUNCH, :WATERFALL, :HIGHHORSEPOWER, :ROCKSLIDE], nature: :ADAMANT, ev: ATKSPE)
                 .set_pkmn(2, :LUDICOLO, 100, [:SWIFTSWIM, :LEVITATE], item: LUDICOLO_CREST, moves: [:RAINDANCE, :GIGADRAIN, :ICEBEAM, :SURF], ev: SPASPE)
                 .set_pkmn(3, :AEGISLASH, 100, [:STANCECHANGE, :LEVITATE], ev: HPDEF)
                 .set_pkmn(4, :LYCANROC, 100, [:TOUGHCLAWS, :LEVITATE], item: :CATALYZER, moves: [:CLOSECOMBAT, :DRILLRUN, :ACCELEROCK, :ROCKSLIDE], form: 2, nature: :JOLLY, ev: ATKSPE)
                 .set_pkmn(5, :NOIVERN, 100, [:TELEPATHY, :LEVITATE], ev: SPASPE)
                 .tclass_name_override("Aero Spirit")

  TrainerModifier.add(:SPIRITM, "Kamina", 0)
                 .set_pkmn(0, :ALAKAZAM, 100, [:MAGICGUARD, :TELEPATHY], moves: [:PSYCHIC, :FOCUSBLAST, :SHADOWBALL, :HIDDENPOWER], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(1, :HONCHKROW, 100, [:MOXIE, :TELEPATHY], moves: [:BRAVEBIRD, :SUPERPOWER, :SUCKERPUNCH, :TAUNT], ev: ATKSPE)
                 .set_pkmn(2, :PORYGONZ, 100, [:ADAPTABILITY, :TELEPATHY], item: :KINGSROCK, moves: [:HIDDENPOWER, :SHADOWBALL, :DARKPULSE, :ICEBEAM], nature: :MODEST, ev: HPSPA)
                 .set_pkmn(3, :MACHAMP, 100, [:NOGUARD, :TELEPATHY], ev: HPATK)
                 .set_pkmn(4, :VOLCARONA, 100, [:SWARM, :TELEPATHY], ev: HPDEF)
                 .set_pkmn(5, :GARCHOMP, 100, [:ROUGHSKIN, :TELEPATHY], ev: ATKSPE)
                 .tclass_name_override("Telepathic Spirit")

  TrainerModifier.add(:SPIRITM, "Cloud", 0)
                 .set_pkmn(0, :POLITOED, 100, [:DRIZZLE, :LIQUEFACTION], nature: :RELAXED, iv: 32, ev: HPDEF)
                 .set_pkmn(1, :TENTACRUEL, 100, [:RAINDISH, :LIQUEFACTION], nature: :CALM, ev: HPSPD)
                 .set_pkmn(2, :FERROTHORN, 100, [:IRONBARBS, :LIQUEFACTION], nature: :RELAXED, ev: HPDEF)
                 .set_pkmn(3, :LUDICOLO, 100, [:SWIFTSWIM, :LIQUEFACTION], moves: [:HYPERVOICE, :GIGADRAIN, :ICEBEAM, :HYPERBEAM], ev: SPASPE)
                 .set_pkmn(4, :KABUTOPS, 100, [:SWIFTSWIM, :LIQUEFACTION], moves: [:ROCKSLIDE, :STONEEDGE, :RETURN, :SUPERPOWER], happiness: 255, ev: ATKSPE)
                 .set_pkmn(5, :SALAMENCE, 100, [:MOXIE, :LIQUEFACTION], moves: [:RETURN, :OUTRAGE, :FLY, :EARTHQUAKE], happiness: 255, ev: ATKSPE)
                 .tclass_name_override("Liquid Spirit")

  TrainerModifier.add(:SPIRITM, "Trevor", 0)
                 .set_pkmn(0, :ROTOM, 100, [:LEVITATE, :DRIZZLE], item: ROTOM_CREST, moves: [:HYDROPUMP, :THUNDERBOLT, :HIDDENPOWER, :PAINSPLIT], hptype: :ICE, ev: HPSPA)
                 .set_pkmn(1, :DRAGONITE, 100, [:MULTISCALE, :CLOUDNINE], item: :CHOICEBAND, moves: [:EARTHQUAKE, :DRAGONCLAW, :FIREPUNCH, :EXTREMESPEED], ev: ATKSPE)
                 .set_pkmn(2, :INFERNAPE, 100, [:MAGICGUARD, :DROUGHT], item: :LIFEORB, moves: [:HEATWAVE, :THUNDERBOLT, :SOLARBEAM, :UTURN], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(3, :SANDSLASH, 100, [:SLUSHRUSH, :SNOWWARNING], item: :LIFEORB, moves: [:IRONHEAD, :ICICLECRASH, :EARTHQUAKE, :SWORDSDANCE], form: 1, nature: :ADAMANT, ev: ATKSPE)
                 .set_pkmn(4, :EXCADRILL, 100, [:SANDRUSH, :SANDSTREAM], item: :LIFEORB, moves: [:IRONHEAD, :EARTHQUAKE, :ROCKSLIDE, :RAPIDSPIN], nature: :JOLLY, ev: ATKSPE)
                 .set_pkmn(5, :HONCHKROW, 100, [:MOXIE, :DELTASTREAM], item: :LIFEORB, moves: [:SUCKERPUNCH, :NIGHTSLASH, :BRAVEBIRD, :SUPERPOWER], nature: :ADAMANT, ev: ATKSPE)
                 .tclass_name_override("Chaotic Spirit")

  TrainerModifier.add(:SPIRITM, "Leo", 0)
                 .set_pkmn(0, :SLOWKING, 100, [:REGENERATOR, :ANALYTIC], item: :LIFEORB, iv: 32, ev: HPSPA)
                 .set_pkmn(1, :STARAPTOR, 100, [:RECKLESS, :ANALYTIC], nature: :JOLLY, ev: ATKSPE)
                 .set_pkmn(2, :ESCAVALIER, 100, [:LANCER, :ANALYTIC], item: :KINGSROCK, moves: [:SWORDSDANCE, :IRONHEAD, :MEGAHORN, :KNOCKOFF], nature: :BRAVE, iv: 32, ev: HPATK)
                 .set_pkmn(3, :TYRANITAR, 100, [:SANDSTREAM, :ANALYTIC], item: :ASSAULTVEST, moves: [:STRENGTH, :CRUNCH, :ROCKSLIDE, :POWERWHIP], iv: 32, ev: HPATK)
                 .set_pkmn(4, :EELEKTROSS, 100, [:LEVITATE, :ANALYTIC], item: :LEFTOVERS, moves: [:COIL, :LIQUIDATION, :DRAINPUNCH, :THUNDERPUNCH], nature: :CAREFUL, ev: HPSPD)
                 .set_pkmn(5, :HYDREIGON, 100, [:LEVITATE, :ANALYTIC], ev: SPASPE)
                 .tclass_name_override("Calculating Spirit")

  TrainerModifier.add(:SPIRITM, "Savage", 0)
                 .set_pkmn(0, :LANTURN, 100, [:VOLTABSORB, :WATERCOMPACTION], item: LANTURN_CREST, moves: [:SCALD, :PROTECT, :VOLTSWITCH, :TOXIC], nature: :CALM, ev: HPSPD)
                 .set_pkmn(1, :LAPRAS, 100, [:HYDRATION, :WATERCOMPACTION], ev: HPSPD)
                 .set_pkmn(2, :TOXAPEX, 100, [:REGENERATOR, :WATERCOMPACTION], item: :BLACKSLUDGE, moves: [:SCALD, :BANEFULBUNKER, :RECOVER, :TOXIC], nature: :CALM, ev: HPSPD)
                 .set_pkmn(3, :SEISMITOAD, 100, [:SWIFTSWIM, :WATERCOMPACTION], ev: SPASPE)
                 .set_pkmn(4, :KINGDRA, 100, [:SWIFTSWIM, :WATERCOMPACTION], item: :ELEMENTALSEED, ev: HPATK)
                 .set_pkmn(5, :GOREBYSS, 100, [:SWIFTSWIM, :WATERCOMPACTION], nature: :MODEST, ev: SPASPD)
                 .tclass_name_override("Rampart Spirit")

  TrainerModifier.add(:SPIRITM, "Owen", 0)
                 .set_pkmn(0, :RHYPERIOR, 100, [:SOLIDROCK, :SANDFORCE], item: :FLAMEPLATE, moves: [:EARTHQUAKE, :FIREPUNCH, :ICEPUNCH, :STEALTHROCK], nature: :ADAMANT, iv: 31, ev: [252, 252, 0, 0, 4, 0])
                 .set_pkmn(1, :NINETALES, 100, [:DROUGHT, :SANDFORCE], ev: SPASPE)
                 .set_pkmn(2, :LEAFEON, 100, [:TINTEDLENS, :SANDFORCE], moves: [:SYNTHESIS, :DIG, :STONEEDGE, :LEAFBLADE], nature: :JOLLY, ev: ATKSPE)
                 .set_pkmn(3, :CHANDELURE, 100, [:FLAMEBODY, :SANDFORCE], moves: [:FLASHCANNON, :HEATWAVE, :SHADOWBALL, :ENERGYBALL], ev: SPASPE)
                 .set_pkmn(4, :CHARIZARD, 100, [:SOLARPOWER, :SANDFORCE], nature: :MODEST, ev: SPASPE)
                 .set_pkmn(5, :SAWSBUCK, 100, [:CHLOROPHYLL, :SANDFORCE], item: SAWSBUCK_CREST, form: 2, nature: :JOLLY, ev: ATKSPE)
                 .tclass_name_override("Arid Spirit")

  TrainerModifier.add(:SPIRITM, "Duster", 0)
                 .set_pkmn(0, :CONKELDURR, 100, [:IRONFIST, :OPENWOUNDS], moves: [:MACHPUNCH, :DRAINPUNCH, :BULKUP, :ICEPUNCH], ev: HPATK)
                 .set_pkmn(1, :ZANGOOSE, 100, [:TOXICBOOST, :OPENWOUNDS], item: ZANGOOSE_CREST, moves: [:FACADE, :CLOSECOMBAT, :KNOCKOFF, :QUICKATTACK], nature: :ADAMANT, ev: ATKSPE)
                 .set_pkmn(2, :CHANDELURE, 100, [:FLAMEBODY, :OPENWOUNDS], ev: ATKSPE)
                 .set_pkmn(3, :AMOONGUSS, 100, [:REGENERATOR, :OPENWOUNDS], ev: [252, 0, 176, 0, 80, 0])
                 .set_pkmn(4, :TYRANITAR, 100, [:SANDSTREAM, :OPENWOUNDS], item: :FLAMEORB, ev: HPATK)
                 .set_pkmn(5, :GLISCOR, 100, [:POISONHEAL, :OPENWOUNDS], moves: [:SWORDSDANCE, :EARTHQUAKE, :ACROBATICS, :PROTECT], ev: ATKSPE)
                 .tclass_name_override("Ruthless Spirit")

  TrainerModifier.add(:SPIRITM, "Jonah", 0)
                 .set_pkmn(0, :NOIVERN, 100, [:INFILTRATOR, :ILLUMINATE], ev: SPASPE)
                 .set_pkmn(1, :CHANDELURE, 100, [:FLAMEBODY, :ILLUMINATE], iv: 32, ev: HPSPA)
                 .set_pkmn(2, :PORYGON2, 100, [:TRACE, :ILLUMINATE], iv: 32, ev: HPDEF)
                 .set_pkmn(3, :AZUMARILL, 100, [:HUGEPOWER, :ILLUMINATE], moves: [:BELLYDRUM, :AQUAJET, :PLAYROUGH, :SUPERPOWER], iv: 32, ev: HPATK)
                 .set_pkmn(4, :AEGISLASH, 100, [:STANCECHANGE, :ILLUMINATE], iv: 32, ev: HPATK)
                 .set_pkmn(5, :MALAMAR, 100, [:CONTRARY, :ILLUMINATE], iv: 32, ev: HPATK)
                 .tclass_name_override("Shining Spirit")

  TrainerModifier.add(:SPIRITM, "Zippo", 0)
                 .set_pkmn(0, :GENGAR, 100, [:LEVITATE, :REFRIGERATE], moves: [:ROUND, :SHADOWBALL, :FOCUSBLAST, :THUNDERBOLT], ev: SPASPE)
                 .set_pkmn(1, :DRAGONITE, 100, [:MULTISCALE, :REFRIGERATE], ev: HPATK)
                 .set_pkmn(2, :STARMIE, 100, [:ILLUMINATE, :REFRIGERATE], ev: SPASPE)
                 .set_pkmn(3, :JOLTEON, 100, [:VOLTABSORB, :REFRIGERATE], item: :LIFEORB, moves: [:THUNDERBOLT, :HURRICANE, :SHADOWBALL, :HYPERVOICE], ev: SPASPE)
                 .set_pkmn(4, :WEAVILE, 100, [:PRESSURE, :REFRIGERATE], item: :LIFEORB, moves: [:KNOCKOFF, :FAKEOUT, :RETURN, :BRICKBREAK], ev: ATKSPE)
                 .set_pkmn(5, :SCIZOR, 100, [:TECHNICIAN, :REFRIGERATE], moves: [:UTURN, :BULLETPUNCH, :SUPERPOWER, :QUICKATTACK], ev: HPATK)
                 .tclass_name_override("Frozen Spirit")

  TrainerModifier.add(:SPIRITM, "Quinn", 0)
                 .set_pkmn(0, :GENGAR, 100, [:LEVITATE, :DOOMSEER], ev: SPASPE)
                 .set_pkmn(1, :SCEPTILE, 100, [:UNBURDEN, :DOOMSEER], moves: [:KNOCKOFF, :LEAFBLADE, :SWORDSDANCE, :EARTHQUAKE], nature: :JOLLY, ev: ATKSPE)
                 .set_pkmn(2, :METAGROSS, 100, [:IRONFIST, :DOOMSEER], item: :LIFEORB, moves: [:METEORMASH, :BULLETPUNCH, :PSYCHIC, :THUNDERPUNCH], nature: :BRAVE, ev: ATKSPA)
                 .set_pkmn(3, :DRAGONITE, 100, [:MULTISCALE, :DOOMSEER], ev: HPATK)
                 .set_pkmn(4, :SLOWBRO, 100, [:REGENERATOR, :DOOMSEER], item: :MAGICALSEED, nature: :MODEST, ev: SPASPE)
                 .set_pkmn(5, :INFERNAPE, 100, [:MAGICGUARD, :DOOMSEER], item: :LIFEORB, moves: [:HEATWAVE, :THUNDERBOLT, :PROTECT, :FAKEOUT], nature: :TIMID, ev: SPASPE)
                 .tclass_name_override("Prophetic Spirit")

  TrainerModifier.add(:SPIRITM, "Troy", 0)
                 .set_pkmn(0, :ROTOM, 100, [:LEVITATE, :NOGUARD], item: ROTOM_CREST, moves: [:AIRSLASH, :THUNDER, :VOLTSWITCH, :HIDDENPOWER], form: 4, nature: :TIMID, ev: SPASPE)
                 .set_pkmn(1, :DRAGONITE, 100, [:MULTISCALE, :NOGUARD], item: :TELLURICSEED, ev: ATKSPE)
                 .set_pkmn(2, :SERPERIOR, 100, [:CONTRARY, :NOGUARD], ev: SPASPE)
                 .set_pkmn(3, :SCIZOR, 100, [:TECHNICIAN, :NOGUARD], item: :TELLURICSEED, ev: HPATK)
                 .set_pkmn(4, :ALAKAZAM, 100, [:MAGICGUARD, :NOGUARD], ev: SPASPE)
                 .set_pkmn(5, :PIDGEOT, 100, [:GALEFORCE, :NOGUARD], item: :CHOICESCARF, moves: [:HURRICANE, :HEATWAVE, :HYPERVOICE, :UTURN], nature: :TIMID, ev: SPASPE)
                 .tclass_name_override("Eagle Spirit")

  TrainerModifier.add(:SPIRITM, "King", 0)
                 .set_pkmn(0, :GENGAR, 100, [:LEVITATE, :MAGICGUARD], ev: SPASPE)
                 .set_pkmn(1, :LUCARIO, 100, [:JUSTIFIED, :MAGICGUARD], ev: ATKSPE)
                 .set_pkmn(2, :WEAVILE, 100, [:PRESSURE, :MAGICGUARD], ev: ATKSPE)
                 .set_pkmn(3, :EXCADRILL, 100, [:SANDRUSH, :MAGICGUARD], ev: ATKSPE)
                 .set_pkmn(4, :TYRANITAR, 100, [:SANDSTREAM, :MAGICGUARD], ev: ATKSPE)
                 .set_pkmn(5, :TOGEKISS, 100, [:SERENEGRACE, :MAGICGUARD], ev: SPASPE)
                 .tclass_name_override("Impervious Spirit")

  TrainerModifier.add(:SPIRITM, "Franz", 0)
                 .set_pkmn(0, :SERPERIOR, 100, [:CONTRARY, :QUEENLYMAJESTY], ev: SPASPE)
                 .set_pkmn(1, :BISHARP, 100, [:DEFIANT, :QUEENLYMAJESTY], ev: HPATK)
                 .set_pkmn(2, :DRUDDIGON, 100, [:SHEERFORCE, :QUEENLYMAJESTY], item: DRUDDIGON_CREST, ev: HPATK)
                 .set_pkmn(3, :REUNICLUS, 100, [:MAGICGUARD, :QUEENLYMAJESTY], ev: HPSPA)
                 .set_pkmn(4, :CHANDELURE, 100, [:FLAMEBODY, :QUEENLYMAJESTY], ev: HPATK)
                 .set_pkmn(5, :ESCAVALIER, 100, [:OVERCOAT, :QUEENLYMAJESTY], ev: HPATK)
                 .tclass_name_override("Royal Spirit")

  TrainerModifier.add(:SPIRITM, "Godot", 0)
                 .set_pkmn(0, :TYPHLOSION, 100, [:FLASHFIRE, :FLAREBOOST], moves: [:HEATWAVE, :HIDDENPOWER, :FOCUSBLAST, :EARTHPOWER], ev: SPASPE)
                 .set_pkmn(1, :SALAZZLE, 100, [:CORROSION, :FLAREBOOST], moves: [:FLAMETHROWER, :SLUDGEBOMB, :NASTYPLOT, :TAUNT], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(2, :ESPEON, 100, [:SPOOKYSEASON, :FLAREBOOST], moves: [:PSYCHIC, :HYPERVOICE, :HIDDENPOWER, :CALMMIND], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(3, :CRADILY, 100, [:STORMDRAIN, :FLAREBOOST], item: :CATALYZER, moves: [:EARTHPOWER, :SUNNYDAY, :RECOVER, :TOXIC], ev: HPDEF)
                 .set_pkmn(4, :LUCARIO, 100, [:JUSTIFIED, :FLAREBOOST], ev: ATKSPE)
                 .set_pkmn(5, :HAXORUS, 100, [:MOLDBREAKER, :FLAREBOOST], item: :LIFEORB, ev: ATKSPE)
                 .tclass_name_override("Burning Spirit")

  TrainerModifier.add(:SPIRITM, "Allan", 0)
                 .set_pkmn(0, :NINETALES, 100, [:DROUGHT, :OWNTEMPO], moves: [:MOONBLAST, :SUBSTITUTE, :FLAMETHROWER, :SOLARBEAM], ev: SPASPE)
                 .set_pkmn(1, :PRIMARINA, 100, [:FLAMEBODY, :OWNTEMPO], item: :CHOICESCARF, moves: [:SCALD, :MOONBLAST, :PSYCHIC, :ENERGYBALL], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(2, :GARDEVOIR, 100, [:TELEPATHY, :OWNTEMPO], ev: SPASPE)
                 .set_pkmn(3, :MILOTIC, 100, [:MARVELSCALE, :OWNTEMPO], item: MILOTIC_CREST, ev: HPDEF)
                 .set_pkmn(4, :LILLIGANT, 100, [:REVEL, :OWNTEMPO], item: :MAGICALSEED, moves: [:REVELATIONDANCE, :QUIVERDANCE, :SLEEPPOWDER, :TOXIC], ev: SPASPE)
                 .set_pkmn(5, :MISMAGIUS, 100, [:LEVITATE, :OWNTEMPO], moves: [:NASTYPLOT, :MOONBLAST, :SHADOWBALL, :MYSTICALFIRE], ev: SPASPE)
                 .tclass_name_override("Unwavering Spirit")

  TrainerModifier.add(:SPIRITM, "Ikaru", 0)
                 .set_pkmn(0, :BRONZONG, 100, [:LEVITATE, :PRISMARMOR], shiny: true, iv: 32, ev: HPSPD)
                 .set_pkmn(1, :ALAKAZAM, 100, [:MAGICGUARD, :PRISMARMOR], shiny: true, nature: :TIMID, ev: SPASPE)
                 .set_pkmn(2, :WEAVILE, 100, [:PRESSURE, :PRISMARMOR], item: :DARKINIUMZ, moves: [:KNOCKOFF, :ICEPUNCH, :ICESHARD, :LOWKICK], shiny: true, ev: ATKSPE)
                 .set_pkmn(3, :MISMAGIUS, 100, [:LEVITATE, :PRISMARMOR], moves: [:NASTYPLOT, :DAZZLINGGLEAM, :SHADOWBALL, :HIDDENPOWER], shiny: true, ev: SPASPE)
                 .set_pkmn(4, :DRAGONITE, 100, [:MULTISCALE, :PRISMARMOR], shiny: true, nature: :ADAMANT, ev: ATKSPE)
                 .set_pkmn(5, :CARRACOSTA, 100, [:STURDY, :PRISMARMOR], shiny: true, ev: ATKSPE)
                 .tclass_name_override("Prismatic Spirit")
                 .forced_fe(:DARKCRYSTALCAVERN)

  TrainerModifier.add(:SPIRITM, "Josh", 0)
                 .set_pkmn(0, :AERODACTYL, 100, [:PRESSURE, :GUTS], moves: [:STEALTHROCK, :TAUNT, :SMACKDOWN, :EARTHQUAKE], ev: ATKSPE)
                 .set_pkmn(1, :FLAREON, 100, [:MAGICGUARD, :GUTS], item: :TOXICORB, moves: [:FACADE, :FLAREBLITZ, :PROTECT, :WISH], nature: :ADAMANT, ev: HPATK)
                 .set_pkmn(2, :SCEPTILE, 100, [:UNBURDEN, :GUTS], ev: ATKSPE)
                 .set_pkmn(3, :CARRACOSTA, 100, [:STURDY, :GUTS], item: :CATALYZER, moves: [:EARTHQUAKE, :ROCKSLIDE, :AQUAJET, :SHELLSMASH], ev: ATKSPE)
                 .set_pkmn(4, :SCRAFTY, 100, [:MOXIE, :GUTS], moves: [:DRAINPUNCH, :BULKUP, :EARTHQUAKE, :ICEPUNCH], ev: HPSPD)
                 .set_pkmn(5, :VOLCARONA, 100, [:FLAMEBODY, :GUTS], item: :WIKIBERRY, ev: SPASPE)
                 .tclass_name_override("Lionheart Spirit")

  TrainerModifier.add(:SPIRITM, "Nate", 0)
                 .set_pkmn(0, :TYRANITAR, 100, [:SANDSTREAM, :SNIPER], item: :CHOPLEBERRY, moves: [:DRAGONDANCE, :CRUNCH, :EARTHQUAKE, :STONEEDGE], ev: ATKSPE)
                 .set_pkmn(1, :GENGAR, 100, [:LEVITATE, :SNIPER], item: :TELLURICSEED, moves: [:SHADOWBALL, :THUNDERBOLT, :DESTINYBOND, :FOCUSBLAST], ev: SPASPE)
                 .set_pkmn(2, :LUCARIO, 100, [:STEADFAST, :SNIPER], item: :TELLURICSEED, moves: [:VACUUMWAVE, :DARKPULSE, :NASTYPLOT, :FOCUSBLAST], nature: :TIMID, ev: SPASPE)
                 .set_pkmn(3, :EXCADRILL, 100, [:SANDRUSH, :SNIPER], item: :TELLURICSEED, moves: [:SWORDSDANCE, :EARTHQUAKE, :IRONHEAD, :ROCKSLIDE], ev: ATKSPE)
                 .set_pkmn(4, :GARCHOMP, 100, [:ROUGHSKIN, :SNIPER], item: :TELLURICSEED, ev: ATKSPE)
                 .set_pkmn(5, :SERPERIOR, 100, [:CONTRARY, :SNIPER], moves: [:LEAFSTORM, :GLARE, :HIDDENPOWER, :DRAGONPULSE], ev: SPASPE)
                 .tclass_name_override("Deadshot Spirit")
                 .forced_fe(:ASHENBEACH)

  TrainerModifier.add(:SPIRITM, "Taro", 0)
                 .set_pkmn(0, :TYRANITAR, 100, [:SANDSTREAM, :MINERALIZE], moves: [:CRUNCH, :DOUBLEEDGE, :EARTHQUAKE, :ICEPUNCH], ev: HPATK)
                 .set_pkmn(1, :MAMOSWINE, 100, [:THICKFAT, :MINERALIZE], item: :CHOICEBAND, moves: [:ICICLECRASH, :EARTHQUAKE, :ICESHARD, :RETURN], ev: ATKSPE)
                 .set_pkmn(2, :EXCADRILL, 100, [:SANDRUSH, :MINERALIZE], moves: [:SWORDSDANCE, :EARTHQUAKE, :IRONHEAD, :ROCKSLIDE], ev: ATKSPE)
                 .set_pkmn(3, :CRADILY, 100, [:STORMDRAIN, :MINERALIZE], item: :TELLURICSEED, moves: [:STOCKPILE, :TOXIC, :RECOVER, :WRINGOUT], ev: HPSPD)
                 .set_pkmn(4, :OMASTAR, 100, [:SHELLARMOR, :MINERALIZE], moves: [:SHELLSMASH, :WRINGOUT, :ICEBEAM, :SCALD], nature: :MODEST, ev: SPASPE)
                 .set_pkmn(5, :GOLURK, 100, [:NOGUARD, :MINERALIZE], moves: [:ROCKPOLISH, :DYNAMICPUNCH, :EARTHQUAKE, :POLTERGEIST], ev: ATKSPE)
                 .tclass_name_override("Telluric Spirit")
                 .forced_fe(:ROCKY)

  TrainerModifier.add(:SPIRITM, "Tenshi", 0)
                 .set_pkmn(0, :METAGROSS, 100, [:CLEARBODY, :GRASSPELT], ev: HPATK)
                 .set_pkmn(1, :SERPERIOR, 100, [:CONTRARY, :GRASSPELT], item: :ASSAULTVEST, moves: [:LEAFSTORM, :HIDDENPOWER, :GIGADRAIN, :DRAGONPULSE], hptype: :FIRE, ev: SPASPE)
                 .set_pkmn(2, :JOLTEON, 100, [:AERILATE, :GRASSPELT], moves: [:THUNDERBOLT, :VOLTSWITCH, :HYPERVOICE, :HIDDENPOWER], ev: SPASPE)
                 .set_pkmn(3, :HAXORUS, 100, [:MOLDBREAKER, :GRASSPELT], ev: HPATK)
                 .set_pkmn(4, :NINETALES, 100, [:DROUGHT, :GRASSPELT], moves: [:SOLARBEAM, :NASTYPLOT, :FLAMETHROWER, :PSYSHOCK])
                 .set_pkmn(5, :SALAMENCE, 100, [:INTIMIDATE, :GRASSPELT], ev: ATKSPE)
                 .tclass_name_override("Sylvan Spirit")

  TrainerModifier.add(:SPIRITF, "Saya", 0)
                 .set_pkmn(0, :ZAPDOS, 100, :PRIMORDIALSEA, item: :LEFTOVERS, moves: [:THUNDER, :HIDDENPOWER, :ROOST, :UTURN], hptype: :WATER, ev: SPASPE)
                 .set_pkmn(1, :SLOWBRO, 100, :REGENERATOR, item: :LEFTOVERS, moves: [:PSYCHIC, :SCALD, :SLACKOFF, :TOXIC], nature: :MODEST, ev: HPSPA)
                 .set_pkmn(2, :DITTO, 100, :IMPOSTER, ev: HPSPE)
                 .set_pkmn(3, :CHANSEY, 100, :NATURALCURE, item: :EVIOLITE, moves: [:PSYCHIC, :THUNDERBOLT, :BLIZZARD, :SOFTBOILED], nature: :BOLD, ev: DEFSPD)
                 .set_pkmn(4, :SNORLAX, 100, :THICKFAT, moves: [:BODYSLAM, :BLIZZARD, :EARTHQUAKE, :THUNDERBOLT], ev: HPSPD)
                 .set_pkmn(5, :MEWTWO, 102, :UNNERVE, item: :LIFEORB, moves: [:PSYSTRIKE, :FLAMETHROWER, :BLIZZARD, :RECOVER], nature: :TIMID, ev: SPASPE)
                 .tclass_name_override("Legendary Spirit")
                 .set_ace("..!!")

}